{
 "title": "FRITZ!Box Home Automation",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "boxtag",
    "label": "FritzBox",
    "query": "from(bucket: \"${bucketname}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field =~ /^ha_.*/)\n  |> keyValues(keyColumns: [\"box\"])\n  |> group()\n  |> keep(columns: [\"box\"])\n  |> distinct(column: \"box\")"
   },
   { "name": "measurement", "label": "InfluxDB measurement", "query": "${VAR_MEASUREMENT}" }
  ]
 },
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last temperatures (all devices)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_temperature\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({\"\": r._value, _measurement: r.name}))"
    }
   ]
  },
  {
   "title": "Temperatures (all devices)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_temperature\" and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name, _value: r._value}))\r\n"
    }
   ]
  },
  {
   "title": "Heating",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heating",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_tist\" and r.box =~ /^${boxtag}$/ and r._value < 253)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name + \" (actual)\", _value: r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_tsoll\" and r.box =~ /^${boxtag}$/ and r._value < 253)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name + \" (set)\", _value: r._value}))\r\n"
      }
     ]
    },
    {
     "title": "Last heating device modes and temperatures",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_boostactive\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, Boost: r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_summeractive\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, Summer: r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_holidayactive\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, Holiday: r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_lock\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, Locked: r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_devicelock\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, \"Device Locked\": r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_tist\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, \"Temp ist\": r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_tsoll\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, \"Temp soll\": r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_komfort\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, \"Temp komfort\": r._value}))\r\n"
      },
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_absenk\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({Device: r.name, \"Temp absenk\": r._value}))\r\n"
      }
     ]
    },
    {
     "title": "Last heating battery status",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_heating_battery\" and r.box =~ /^${boxtag}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({\"\": r._value, _measurement: r.name}))"
      }
     ]
    },
    {
     "title": "Window states",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field =~ /^ha_heating_windowopenactive?$/ and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name, _value: if r._value != 0 then true else false}))\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_powermeter_power\" and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _measurement: r.name, _field: strings.replaceAll(v: r._field, t: \"ha_powermeter_\", u: \"\")}))"
      },
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"ha_powermeter_voltage\" and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _measurement: r.name, _field: strings.replaceAll(v: r._field, t: \"ha_powermeter_\", u: \"\")}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Device Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Details",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box =~ /^${boxtag}$/ and \n    (\n      r._field == \"ha_fw_version\" or\n      r._field == \"ha_product_name\" or\n      r._field == \"ha_manufacturer\" or\n      r._field == \"ha_devicefunctions\" or\n      r._field == \"ha_hun_fun_interfaces\" or\n      r._field == \"ha_hun_fun_unittype\" or\n      r._field == \"ha_device_present\" or \n      r._field == \"ha_device_present\"\n    )\n  )\n  |> last()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n"
      }
     ]
    },
    {
     "title": "Device Details",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\n  |> range(start: -12h)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box =~ /^${boxtag}$/ and \n    (\n      r._field == \"ha_battery_percent\" or\n      r._field == \"ha_product_name\" or\n      r._field == \"ha_battery_low\" or\n      r._field == \"ha_switch_state\" or\n      r._field == \"ha_switch_mode\" or\n      r._field == \"ha_switch_lock\" or\n      r._field == \"ha_switch_devicelock\" or \n      r._field == \"ha_simpleonoff_state\"\n    )\n  )\n  |> last()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch states",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field =~ /^ha_switch_state$/ and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name, _value: if r._value != 0 then true else false}))\r\n"
      }
     ]
    },
    {
     "title": "Device states",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field =~ /^ha_simpleonoff_state$/ and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name, _value: if r._value != 0 then true else false}))\r\n"
      }
     ]
    },
    {
     "title": "Alert states",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "query": "from(bucket: \"${bucketname}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field =~ /^ha_alert$/ and r.box =~ /^${boxtag}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first)\r\n  |> fill(usePrevious: true)\r\n  |> map(fn: (r) => ({_time: r._time, _field: r.name, _value: if r._value != 0 then true else false}))\r\n"
      }
     ]
    }
   ]
  }
 ]
}